name: smoke-information

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
    PERL_SKIP_TTY_TEST: 1

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
            fetch-depth: 10
      - name: Involved authors
        run: |
            if [ -n "${GITHUB_HEAD_REF}" ]; then
                echo "Pull request authors"
                # env
                echo git merge-base origin/${GITHUB_BASE_REF} ${GITHUB_HEAD_REF}
                branch_off=$(git merge-base origin/${GITHUB_BASE_REF} ${GITHUB_HEAD_REF})
                git log --pretty=format:"Author: %an <%ae>" $branch_off..${GITHUB_SHA}^2
            else
              true; # no failures on personal clones
            fi
