name: smoke-linux-i386

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:


jobs:
  perl:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    # https://hub.docker.com/r/i386/ubuntu/
    container:
        image: i386/ubuntu:latest
        env:
          PERL_SKIP_TTY_TEST: 1
          CONTINUOUS_INTEGRATION: 1
          WORKSPACE: ${{ github.workspace }}

    strategy:
        fail-fast: false
        matrix:
            # exercise a variety of build options
            # threads often cause build issues
            CONFIGURE_ARGS:
              - "-Dusedevel"

    steps:
      - uses: actions/checkout@v1
        with:
            fetch-depth: 10
      - name: Install System dependencies
        run: |
            apt-get update ||:
            apt-get -y install build-essential
      - name: Configure
        run: |
            ./Configure -des -Dusedevel ${{ matrix.CONFIGURE_ARGS }} -Dprefix="$HOME/perl-blead" -DDEBUGGING
      - name: Build
        run: |
            make -j2
      - name: Run Tests
        run: |
            TEST_JOBS=2 make -j2 test
